export const data = [
    {
        id: 1,
        placeName: "Salar de Uyuni, Bolivia",
        image:"https://images.unsplash.com/photo-1571422657325-63704f9273ea?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80",
        description: "Bolivia’s Salar de Uyuni is considered one of the most extreme and remarkable vistas in all of South America, if not Earth. Stretching more than 4,050 square miles of the Altiplano, it is the world’s largest salt flat, left behind by prehistoric lakes evaporated long ago. Here, a thick crust of salt extends to the horizon, covered by quilted, polygonal patterns of salt rising from the ground.",
        source:"Nationalgeographic.com",
        showMore: false,
    },
    {
    id: 2,
        placeName: "Queensland, Australia",
        image:"https://images.unsplash.com/photo-1600791200866-aa1a25e13191?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2027&q=80",
        description: "The Whitsundays are some of the most beautiful islands on the planet, with swirling, white sand and waves of blue-green water that swirl around into wavy patterns that mesmerize visitors. The islands (there are 74 of them, all in the heart of the Great Barrier Reef) are great for walking and exploring. You’ll find lonely, deserted beaches and some of Australia’s oldest archaeological sites. But the best way to appreciate the majesty of the blue bays and brilliant white sandbars is by plane.",
        source:"Nationalgeographic.com",
        showMore: false,
    },
    {
        id: 3,
            placeName: "Zhangye, China",
            image:"https://images.unsplash.com/photo-1603622913270-f54dcb0d792d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80",
            description: "Zhangye is located in the middle of Gansu, where Gansu is narrowest. It features unique and beautiful natural landscapes, with a 50-square-kilometer (19-square-mile) area of celebrated Danxia landforms, typified by orangey-red cliffs and rainbow ridges. Zhangye appears to be one of the filming locations of Disney's Mulan. In the official trailer, at 1 minute 56 seconds, when Mulan is riding across a colorful mountain ridge, that mountainous landscape is very likely to be Zhangye Danxia National Geological Park.",
            source:"Chinahighlights.com",
            showMore: false,
    },
    {
        id: 4,
            placeName: "Door to Hell, Turkmenistan",
            image:"https://images.unsplash.com/photo-1551668478-1feed82a065d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2065&q=80",
            description: "The Door to Hell is a continually burning crater located in remote Turkmenistan. Adventurer George Kourounis describes being the first person to enter the Door to Hell and what he found when he reached the bottom.",
            source:"Nationalgeographic.com",
            showMore: false,
    },
    {
        id: 5,
            placeName: "Lake Natron, Tanzania",
            image:"https://images.unsplash.com/photo-1667550577898-53e9750c6316?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1935&q=80",
            description: "Apart from sometimes turning red, another reason that Lake Natron is so unusual is that it's incredibly caustic (alkaline) from the nearby volcano. This makes it poisonous to most animals. Animal and bird corpses can be found in and around the lake. This is why we refer to Lake Natron as Tanzania’s beautiful but deadly red lake.",
            source:"Followalice.com",
            showMore: false,
    },
    {
        id: 6,
            placeName: "Deception Island, Antarctica",
            image:"https://images.unsplash.com/photo-1647411625356-1d892caaa229?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1974&q=80",
            description: "This ring-shaped island, which is actually the caldera of an active volcano, is a popular part of our Antarctic Peninsula cruises. The caldera has a diameter of about 15 km (nine miles) with a narrow entrance on one side known as Neptune’s Bellows. We can sometimes sail through this spectacular passage into the flooded crater beyond. Since the Deception Island volcano is active, geothermal activity still takes place inside the caldera. Sea water temperatures of 70°C (150°F) have been recorded, and eruptions occurred as recently as 1970. Sealers, whalers, explorers, and scientists have been sailing into the island’s Port Foster since 1820, and remains of these expeditions can still be seen.",
            source:"Oceanwide-expeditions.com",
            showMore: false,
    },
    {
        id: 7,
            placeName: "Pitons, St Lucia",
            image:"https://images.unsplash.com/photo-1676725011766-f66e62d9cd0f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1975&q=80",
            description: "While Saint Lucia offers some of the most beautiful scenery in the world none can top the majestic Pitons, the island’s iconic mountains. Said to be the most photographed site in the Caribbean and the most famous mountain pair on earth, the Pitons are a must-see for anyone who visits the island.",
            source:"Traveltips.org",
            showMore: false,
    },
    {
        id: 8,
            placeName: "Churchill, Manitoba, Canada",
            image:"https://images.unsplash.com/photo-1577941533467-0b0b8166d638?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80",
            description: "One of the most amazing destinations in the province, Churchill, Manitoba is known as the polar bear capital of the world. And while seeing polar bears in the wild is certainly a once-in-a-lifetime experience, there are many other things to do in Churchill, too. From the Northern Lights to kayaking with belugas to learning about the local Inuit culture, we’ve put together this guide for you with everything you need to know about Churchill. We’ve listed tour companies, where to stay, where to eat, and everything there is to do in the small community, no matter the season. Read on for your ultimate guide to visiting Churchill, Manitoba.",
            source:"Roadtripmanitoba.com",
            showMore: false,
    },
    {
        id: 9,
            placeName: "Amsterdam, Netherlands",
            image:"https://images.unsplash.com/photo-1584003564911-a7a321c84e1c?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1884&q=80",
            description: "Picture-perfect canals lined with gabled houses from the Golden Age, a remarkable art collection ranging from Rembrandt to Mondrian, more culture per capita than any other European capital, its own distinctive style of modernist architecture, enough day trips and nightlife options to fill a lifetime, and free-spirited and friendly folks that, somehow, all speak English: Amsterdam is a richly varied treasure-trove of attractions. —Sander Groen",
            source:"Nationalgeographic.com",
            showMore: false,
    },
    {
        id: 10,
            placeName: "Easter Island, Chile",
            image:"https://images.unsplash.com/photo-1579665063783-77579f0a38a3?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1974&q=80",
            description: "Although Easter Island is known for its mysterious moai statues, the remote Polynesian island has much more to explore. About 42 percent of this island is Rapa Nui National Park, a World Heritage property inscribed in 1995 to preserve the natural and cultural wonders of the Chilean territory. Go beyond Easter Island’s man-made marvels to understand the inspiration for the Rapa Nui peoples’ megalithic achievements.",
            source:"Nationalgeographic.com",
            showMore: false,
    },
]